### PR TITLE
Fix windows os normalizePath

### PR DESCRIPTION
**Pull request by GKhelio**

### CODE REVIEW

**Comment by caoxiemeihao** [comment]
Thanks for you PR.  
Perhaps we want to make the fix at https://github.com/vite-plugin/vite-plugin-dynamic-import/blob/174718b54b7af72fa9c1ed571bebbb1533ad204c/src/index.ts#L192 instead.

You can resubmit a new PR. 😅

**Comment by GKhelio** [comment]
The error is in resolved.import.resolved `'..\\..\\..\\../components/**.vue'`

**Comment by caoxiemeihao** [comment]
Changes should be done in "aa" because "dd" is needed to maintain compatibility with Vite

**Comment by GKhelio** [comment]
@caoxiemeihao  (@rollup/plugin-dynamic-import-vars) has the same problem with windows os,

Also if you do not want to test the change you can mount a virtual machine with windows os and perform the tests yourself, you will see how I am right.

**Comment by caoxiemeihao** [comment]
@GKhelio Thanks for your explain, maybe change here to be better.
https://github.com/vite-plugin/vite-plugin-dynamic-import/blob/174718b54b7af72fa9c1ed571bebbb1533ad204c/src/resolve.ts#L85

```diff
// line 85
- let relp = path.relative(path.dirname(normalId), node_modules)
+ let relp = path.posix.relative(path.dirname(normalId), node_modules)

// line 124
- let relativePath = path.relative(
+ let relativePath = path.posix.relative(
```

**Comment by GKhelio** [comment]
@caoxiemeihao I just tested the fix with `posix` and it works perfectly.
I make a new PR

**Comment by caoxiemeihao** [comment]
> @caoxiemeihao I just tested the fix with `posix` and it works perfectly. I make a new PR #15

Good job! 👍

**Pull request closed without merging**
